spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/budgetops}
    username: ${SPRING_DATASOURCE_USERNAME:budgetops}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# 도커에서는 실제 도메인으로 리다이렉트
app:
  oauth2:
    redirect-uri: https://budgetops.work/oauth/callback
iamport:
  api:
    key: ${IAMPORT_API_KEY:test_api_key}
    secret: ${IAMPORT_API_SECRET:test_api_secret}

logging:
  level:
    org.hibernate.SQL: debug